[pytest]
testpaths = .
python_files = test_*.py
python_functions = test_*
addopts = -v

markers =
    smoke: быстрая проверка
    slow: долгие тесты
    api: тесты API
    ui: тесты интерфейса

log_cli = true
log_cli_level = INFO
log_cli_format = %(asctime)s [%(levelname)s] %(name)s: %(message)s
log_cli_date_format = %H:%M:%S